name: Lint YAML
description: Lint YAML files with yamllint
runs:
  using: composite
  steps:
    - name: Lint YAML files with yamllint
      run: >
        yamllint . -d "{extends: default, rules: {line-length:
        {allow-non-breakable-words: true, allow-non-breakable-inline-mappings:
        true}}}" --no-warnings
      shell: bash
