name: Lint YAML
description: Lint YAML files with yamllint
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Check for yamllint config
      run: |
        if [ -e ./.yamllint ]; then
            echo "A .yamllint config file has been found in the root of this branch and will be used in this workflow."
        else
            echo "No .yamllint config file has been found in the root of this branch and so the standard Data Engineering config will used."
            curl https://moj-analytical-services.github.io/.github/configs/data-engineering/yamllint > .yamllint
        fi
      shell: bash
    - name: Install yamllint
      run: |
        python -m pip install --upgrade pip
        pip install yamllint
      shell: bash
    - name: Lint YAML files with yamllint
      run: >
        yamllint .
      shell: bash
