name: Lint YAML
description: Lint YAML files with yamllint
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install yamllint
      run: |
        python -m pip install --upgrade pip
        pip install flake8 yamllint
      shell: bash
    - name: Lint YAML files with yamllint
      run: >
        yamllint . -d "{extends: default, rules: {line-length:
        {allow-non-breakable-words: true, allow-non-breakable-inline-mappings:
        true}}}" --no-warnings
      shell: bash
